-- MySQL Script generated by MySQL Workbench
-- Wed Oct  2 11:27:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Workout
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Workout` ;

-- -----------------------------------------------------
-- Schema Workout
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Workout` DEFAULT CHARACTER SET utf8 ;
USE `Workout` ;

-- -----------------------------------------------------
-- Table `Workout`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Workout`.`User` ;

CREATE TABLE IF NOT EXISTS `Workout`.`User` (
  `User_ID` INT NOT NULL,
  `Weight` DOUBLE NOT NULL,
  `Height` DOUBLE NOT NULL,
  `Age` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Workout`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Workout`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `Workout`.`Schedule` (
  `Date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Workout`.`Workout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Workout`.`Workout` ;

CREATE TABLE IF NOT EXISTS `Workout`.`Workout` (
  `workout_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `heartrate` INT NOT NULL,
  `calorielost` INT NOT NULL,
  `User_User_ID` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `Schedule_Date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`workout_id`),
  INDEX `fk_workout_User_idx` (`User_User_ID` ASC) VISIBLE,
  INDEX `fk_Workout_Schedule1_idx` (`Schedule_Date` ASC) VISIBLE,
  CONSTRAINT `fk_workout_User`
    FOREIGN KEY (`User_User_ID`)
    REFERENCES `Workout`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Workout_Schedule1`
    FOREIGN KEY (`Schedule_Date`)
    REFERENCES `Workout`.`Schedule` (`Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
